### ISSUE TITLE
Can you build a feature to let me remove ads for web monetized users?

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/coil-wordpress-plugin#63]
The plugin currently allows content in Gutenberg blocks to be hidden (or shown) for web monetized users. Can you build a feature to let me remove ad scripts for web monetized users?

Example scenario: We're using a modification of the Web Monetization Remove Ads script (https://webmonetization.org/docs/remove-ads). We have multiple ad blocks from different providers and have to manually target based on CSS class name to remove them. We'd like to target those through the plugin rather than hardcoded JS in the template files.

**Comment by pragmatic-web** [comment]
I think we'd want to be very careful here. Without legal advice I couldn't be sure but I'd bet that hiding ads in this way is something that would be in breach of most ad services' Terms of Service. Clearly we wouldn't want the ire of the Google Ads team to be aimed at Coil or any of the plugin's users.

However, I think there are likely cases where hiding ads is NOT against terms of service - and indeed where they may be benefit to being able to show/hide arbitrary DOM elements (of course a user could use this to target ads too, but we couldn't prevent that - maybe just add a warning to make sure they're aware of the risks).

So maybe a refined proposal is:

* Similar to the way that post types can be set to different settings in the current Coil settings
* And similar to the way that post excerpts can be targeted through CSS DOM selectors
* We could allow folks to add arbitrary DOM selectors and control their Web Monetization interaction if any

One could imagine a settings tab with three 'buckets' containing *-separated CSS selectors so that folks can add as many CSS selectors for targeting with different behaviours - hide, show, public but monetized, etc.

Interesting one.
