### ISSUE TITLE
'Get Coil to Access' button and call-to-action still shown even though I'm a member and the extension is streaming

### ISSUE THREAD

**Issue by cyberdees** [coilhq/coil-wordpress-plugin#77]
<img width="1451" alt="Screen Shot 2020-08-04 at 10 33 13 AM" src="https://user-images.githubusercontent.com/526538/89278526-237e0800-d63e-11ea-9c2b-0ae9556a2b85.png">

In the attachment, from visiting Pittsburgh Unfiltered [https://pghunfiltered.com/] — my expectation that the 'Get Coil to Access' button and CTA is not shown at all, since the browser has already detected that I am a member and am streaming...

**Comment by melissahenderson** [comment]
Hi @cyberdees, 

We need some more information in order to troubleshoot.
- What theme are they using? Is it one they created on their own?
- What values are in the CSS Selectors field within the Coil plugin settings (Global Settings tab)?

Just a preliminary look makes me think it's an issue with the CSS Selectors. Setting the field to one of these might help:
- article .entry-content
- article .post-content
- article .post-content .entry-content (I'm less sure about this one)

This might also help: https://help.coil.com/for-creators/wordpress-plugin#everyone-no-one-can-see-my-monetized-content-why

**Comment by MattSaincome** [comment]
@melissahenderson I started an email thread to get all this info, and will be around to assist however you need with testing and creator communication!

**Comment by MWcompeff** [comment]
I have a similar problem. I am using Wordpress with the template "Generate Press". The blog is set to use excerpts, not the readmore-Tag. 

1) When I surf as a Coil member onto a category feed (a page listing all current blog items of a certain category), monetized articles show as "the content in this article is for coil members only", although my coil browser addin is streaming.

2) When I click on the heading to switch over to the entire article, the full article is shown correctly, in full length, as it should for coil members. So thats fine.

here's the demo:
https://compeff-blog.de/2020/this-is-a-coil-test-article/

![coil_article_list_doesnt_unlock_excerpt](https://user-images.githubusercontent.com/63209411/90066993-c560bd00-dcee-11ea-958c-05c001eb66b1.png)

**Comment by melissahenderson** [comment]
@MWcompeff I believe the issue you're seeing is related to this: https://github.com/coilhq/coil-wordpress-plugin/issues/46. 

Can you take a look at that issue and let us know?

**Comment by melissahenderson** [comment]
Changing the CSS selectors did help some, but didn't fully resolve the issues. I've isolated a specific issue with the Hemingway theme and embedded videos, so I've opened https://github.com/coilhq/coil-wordpress-plugin/issues/81. 

As far as Dee's original comment:

> my expectation that the 'Get Coil to Access' button and CTA is not shown at all, since the browser has already detected that I am a member and am streaming...

The "home" page is acting as designed, though we recognize that it's confusing. That issue is covered here: https://github.com/coilhq/coil-wordpress-plugin/issues/46. 

Closing this issue.
